openapi: 3.0.0
info:
  title: API de Profesores y Cursos
  description: API para gestionar registros de profesores y cursos.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Servidor de desarrollo

paths:
  /profesores:
    get:
      summary: Obtener todos los profesores
      responses:
        '200':
          description: Un arreglo JSON de profesores
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
                    especialidad:
                      type: string
                    dni:
                      type: string
                    telefono:
                      type: string
    post:
      summary: Añadir un nuevo profesor
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                especialidad:
                  type: string
                dni:
                  type: string
                telefono:
                  type: string
      responses:
        '200':
          description: Profesor creado exitosamente

  /profesores/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un profesor por ID
      responses:
        '200':
          description: Un objeto de profesor
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  especialidad:
                    type: string
                  dni:
                    type: string
                  telefono:
                    type: string
        '404':
          description: Profesor no encontrado
    delete:
      summary: Eliminar un profesor por ID
      responses:
        '200':
          description: Profesor eliminado exitosamente
        '404':
          description: Profesor no encontrado

  /cursos:
    get:
      summary: Obtener todos los cursos
      responses:
        '200':
          description: Un arreglo JSON de cursos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre_curso:
                      type: string
                    num_creditos:
                      type: integer
                    idProfesor:
                      type: integer
    post:
      summary: Añadir un nuevo curso
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nombre_curso:
                  type: string
                num_creditos:
                  type: integer
                idProfesor:
                  type: integer
      responses:
        '200':
          description: Curso creado exitosamente

  /cursos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un curso por ID
      responses:
        '200':
          description: Un objeto de curso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre_curso:
                    type: string
                  num_creditos:
                    type: integer
                  idProfesor:
                    type: integer
        '404':
          description: Curso no encontrado
    delete:
      summary: Eliminar un curso por ID
      responses:
        '200':
          description: Curso eliminado exitosamente
        '404':
          description: Curso no encontrado

  /cursos/{id}/version2:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un curso simplificado por ID (solo idCurso y idProfesor)
      responses:
        '200':
          description: Un objeto con idCurso e idProfesor
          content:
            application/json:
              schema:
                type: object
                properties:
                  idCurso:
                    type: integer
                  idProfesor:
                    type: integer
        '404':
          description: Curso no encontrado

components:
  schemas:
    Profesor:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        especialidad:
          type: string
        dni:
          type: string
        telefono:
          type: string
    Curso:
      type: object
      properties:
        id:
          type: integer
        nombre_curso:
          type: string
        num_creditos:
          type: integer
        idProfesor:
          type: integer
